FROM node:22-alpine
WORKDIR /app
COPY . .
RUN npm ci
ARG NEXT_PUBLIC_WS_HOST
ENV NEXT_PUBLIC_WS_HOST=$NEXT_PUBLIC_WS_HOST
# Réglages du site (voir apps/web/lib/site.ts) — vides = fonctionnalité cachée.
ARG NEXT_PUBLIC_SUPPORT_URL=""
ARG NEXT_PUBLIC_CONTACT_EMAIL=""
ARG NEXT_PUBLIC_LEGAL_NAME=""
ARG NEXT_PUBLIC_LEGAL_ADDRESS=""
ARG NEXT_PUBLIC_LEGAL_SIRET=""
ARG NEXT_PUBLIC_LEGAL_MEDIATOR=""
ENV NEXT_PUBLIC_SUPPORT_URL=$NEXT_PUBLIC_SUPPORT_URL \
    NEXT_PUBLIC_CONTACT_EMAIL=$NEXT_PUBLIC_CONTACT_EMAIL \
    NEXT_PUBLIC_LEGAL_NAME=$NEXT_PUBLIC_LEGAL_NAME \
    NEXT_PUBLIC_LEGAL_ADDRESS=$NEXT_PUBLIC_LEGAL_ADDRESS \
    NEXT_PUBLIC_LEGAL_SIRET=$NEXT_PUBLIC_LEGAL_SIRET \
    NEXT_PUBLIC_LEGAL_MEDIATOR=$NEXT_PUBLIC_LEGAL_MEDIATOR
RUN npm run build --workspace @subtitles-party/web
ENV NODE_ENV=production
ENV PORT=8080
ENV HOSTNAME=0.0.0.0
EXPOSE 8080
CMD npm run start --workspace @subtitles-party/web
