// Personnes mystères de « Devine qui » : personnages et personnalités que
// (presque) tout le monde connaît en France. L'indice aide le Maître du
// secret à répondre juste.
import type { Celebrity } from "./types";

const C = (name: string, hint: string, ...aliases: string[]): Celebrity => ({ name, hint, aliases });

const BUILTIN: Celebrity[] = [
  // Personnages de fiction
  C("Harry Potter", "Sorcier à lunettes, saga de livres et films"),
  C("Hermione Granger", "Sorcière très douée, amie de Harry Potter", "Hermione"),
  C("Dark Vador", "Méchant de Star Wars, casque noir", "Dark Vader", "Darth Vader", "Anakin Skywalker"),
  C("Yoda", "Petit maître Jedi vert de Star Wars", "Maître Yoda"),
  C("Mario", "Plombier moustachu de Nintendo", "Super Mario"),
  C("Pikachu", "Pokémon jaune électrique"),
  C("Sonic", "Hérisson bleu ultra-rapide de jeu vidéo"),
  C("Spider-Man", "Super-héros araignée de Marvel", "Spiderman", "Peter Parker", "Homme araignée"),
  C("Batman", "Super-héros chauve-souris de Gotham", "Bruce Wayne"),
  C("Superman", "Super-héros venu de Krypton", "Clark Kent"),
  C("Wonder Woman", "Super-héroïne amazone de DC"),
  C("Hulk", "Géant vert de Marvel", "Bruce Banner"),
  C("Iron Man", "Super-héros en armure de Marvel", "Tony Stark"),
  C("Astérix", "Petit Gaulois moustachu, BD", "Asterix"),
  C("Obélix", "Gaulois costaud tombé dans la potion", "Obelix"),
  C("Tintin", "Reporter à la houppe, BD belge"),
  C("Lucky Luke", "Cow-boy qui tire plus vite que son ombre"),
  C("Shrek", "Ogre vert de dessin animé"),
  C("Homer Simpson", "Père de famille des Simpson", "Homer"),
  C("Bob l'éponge", "Éponge jaune qui vit sous la mer", "Bob l eponge", "Bob"),
  C("Mickey", "Souris de Disney", "Mickey Mouse"),
  C("Cendrillon", "Princesse Disney qui perd sa pantoufle de verre"),
  C("Blanche-Neige", "Princesse Disney et les sept nains", "Blanche Neige"),
  C("Elsa", "Reine des neiges de Disney", "La Reine des neiges"),
  C("Simba", "Lionceau du Roi Lion"),
  C("Buzz l'Éclair", "Ranger de l'espace de Toy Story", "Buzz"),
  C("Woody", "Cow-boy jouet de Toy Story"),
  C("Le Petit Prince", "Personnage de Saint-Exupéry, sa rose et sa planète", "Petit Prince"),
  C("Sherlock Holmes", "Détective anglais à la loupe", "Sherlock"),
  C("James Bond", "Espion britannique, agent 007", "007"),
  C("Arsène Lupin", "Gentleman cambrioleur français", "Lupin"),
  C("Le Père Noël", "Barbe blanche, distribue des cadeaux", "Pere Noel", "Santa Claus"),
  C("Dracula", "Vampire de Transylvanie"),
  C("Zorro", "Justicier masqué qui signe d'un Z"),
  C("Robin des Bois", "Archer qui vole aux riches", "Robin Hood"),
  C("Jack Sparrow", "Pirate des Caraïbes", "Capitaine Jack Sparrow"),
  C("Indiana Jones", "Archéologue aventurier au chapeau et au fouet", "Indy"),
  C("Gandalf", "Magicien du Seigneur des anneaux"),
  C("Voldemort", "Mage noir de Harry Potter", "Lord Voldemort", "Tom Jedusor"),
  C("Garfield", "Chat orange qui adore les lasagnes"),
  C("Scooby-Doo", "Chien peureux qui résout des mystères", "Scooby Doo", "Scooby"),
  C("Picsou", "Canard milliardaire de Disney", "Oncle Picsou"),
  C("Lara Croft", "Aventurière de Tomb Raider"),
  C("Pinocchio", "Pantin de bois dont le nez s'allonge"),
  C("Kirikou", "Petit garçon africain de dessin animé"),
  C("Gollum", "Créature obsédée par « son précieux »", "Smeagol"),
  C("Rocky Balboa", "Boxeur de cinéma, Philadelphie", "Rocky"),
  C("Wolverine", "Mutant aux griffes de Marvel", "Logan"),
  // Personnalités historiques
  C("Napoléon", "Empereur français", "Napoleon", "Napoléon Bonaparte", "Bonaparte"),
  C("Jeanne d'Arc", "Héroïne française du Moyen Âge", "Jeanne d Arc"),
  C("Louis XIV", "Le Roi-Soleil, Versailles", "Louis 14", "Le Roi Soleil"),
  C("Cléopâtre", "Reine d'Égypte", "Cleopatre"),
  C("Jules César", "Général et dictateur romain", "Cesar", "Jules Cesar"),
  C("Marie Curie", "Scientifique, deux prix Nobel", "Marie Curie"),
  C("Albert Einstein", "Physicien, E = mc²", "Einstein"),
  C("Charles de Gaulle", "Général et président français", "De Gaulle", "Le général de Gaulle"),
  C("Victor Hugo", "Écrivain des Misérables", "Hugo"),
  C("Molière", "Dramaturge du XVIIe siècle", "Moliere"),
  C("Mozart", "Compositeur autrichien prodige", "Wolfgang Amadeus Mozart"),
  C("Léonard de Vinci", "Peintre de la Joconde", "Leonard de Vinci", "De Vinci", "Leonardo da Vinci"),
  C("Pablo Picasso", "Peintre espagnol, cubisme", "Picasso"),
  C("Christophe Colomb", "Navigateur, Amérique en 1492", "Colomb"),
  // Personnalités contemporaines
  C("Zinédine Zidane", "Footballeur français, champion du monde 98", "Zidane", "Zizou"),
  C("Kylian Mbappé", "Footballeur français star", "Mbappe"),
  C("Teddy Riner", "Judoka français multi-champion", "Riner"),
  C("Usain Bolt", "Sprinteur jamaïcain le plus rapide du monde", "Bolt"),
  C("Serena Williams", "Championne de tennis américaine", "Serena"),
  C("Michael Jackson", "Roi de la pop, moonwalk", "MJ", "Jackson"),
  C("Beyoncé", "Chanteuse américaine superstar", "Beyonce", "Queen B"),
  C("Céline Dion", "Chanteuse québécoise, Titanic", "Celine Dion"),
  C("Johnny Hallyday", "Rockeur français, « Allumer le feu »", "Johnny"),
  C("Édith Piaf", "Chanteuse de « La Vie en rose »", "Piaf", "Edith Piaf"),
  C("Stromae", "Chanteur belge, « Alors on danse »"),
  C("Aya Nakamura", "Chanteuse française, « Djadja »", "Aya"),
  C("Omar Sy", "Acteur français, Intouchables, Lupin"),
  C("Louis de Funès", "Acteur comique culte (Le Gendarme)", "De Funes", "Louis de Funes"),
  C("Thomas Pesquet", "Astronaute français", "Pesquet"),
  C("Squeezie", "Youtubeur français le plus suivi"),
  C("Elon Musk", "Patron de Tesla et SpaceX", "Musk"),
  C("Barack Obama", "Ancien président des États-Unis", "Obama"),
  C("Charlie Chaplin", "Acteur du muet, canne et chapeau melon", "Charlot", "Chaplin"),
  C("Lionel Messi", "Footballeur argentin génie", "Messi"),
];

export function guessWhoBank(): Celebrity[] {
  return BUILTIN.slice();
}
